/**
 * 既存 members の name / furigana を first_name, last_name / first_furigana, last_furigana に分割するバッチ。
 * 使い方: npx tsx scripts/split-members-name.ts [_Prep/members_rows.csv]
 * 出力: SQL UPDATE 文を stdout に出す。045 マイグレーション適用後に Supabase SQL Editor で実行する。
 */

import * as fs from "fs";
import * as path from "path";

const CSV_PATH =
  process.argv[2] ?? path.join(process.cwd(), "_Prep", "members_rows.csv");

/** 1文字姓（姓が1文字の名字）。3文字名前用 */
const ONE_CHAR_SURNAMES = new Set(
  "林原森谷池井伊吉西安石藤東北南中上下山口本木松竹梅目米貝車金長高小大新古多".split("")
);

function hasKanji(s: string): boolean {
  return /[\u4e00-\u9faf\u3400-\u4dbf]/.test(s);
}

/**
 * 姓名の境界文字数（姓の長さ）を推定する。
 * - 4文字以上: 原則 2 文字が姓（佐藤匠、田村晶子）
 * - 3文字: 1文字姓リストに含まれる場合は 1、それ以外は 2
 * - 2文字: 1 が姓
 * - 1文字 or カナのみ: 姓なし（全体を名とする）
 */
function inferLastNameLength(name: string): number {
  const t = name.trim();
  if (!t) return 0;
  if (t.length >= 4) return 2;
  if (t.length === 3)
    return ONE_CHAR_SURNAMES.has(t[0]!) ? 1 : 2;
  if (t.length === 2) return 1;
  return 0;
}

/**
 * フリガナを姓・名で分割する長さ（姓側の文字数）を推定。
 * - 2文字姓 → 3カナ（サトウ、タムラ、ミヤケ）
 * - 1文字姓 → 3カナ（ハヤシ）
 */
function inferLastFuriganaLength(lastNameLength: number): number {
  if (lastNameLength <= 0) return 0;
  if (lastNameLength === 1) return 3;
  return lastNameLength + 1;
}

export function splitNameAndFurigana(
  name: string,
  furigana: string | null
): {
  last_name: string;
  first_name: string;
  last_furigana: string;
  first_furigana: string;
} {
  const n = (name ?? "").trim();
  const f = (furigana ?? "").trim();

  if (!n) {
    return {
      last_name: "",
      first_name: "",
      last_furigana: "",
      first_furigana: f,
    };
  }

  // 漢字が含まれない（カナ・アルファベットのみ）場合は単一の名として扱う
  if (!hasKanji(n)) {
    return {
      last_name: "",
      first_name: n,
      last_furigana: "",
      first_furigana: f,
    };
  }

  const lastLen = inferLastNameLength(n);
  const last_name = lastLen > 0 ? n.slice(0, lastLen) : "";
  const first_name = lastLen > 0 ? n.slice(lastLen) : n;

  if (!f) {
    return {
      last_name,
      first_name,
      last_furigana: "",
      first_furigana: "",
    };
  }

  const lastFuriganaLen = Math.min(
    inferLastFuriganaLength(lastLen),
    Math.max(0, f.length - 1)
  );
  const last_furigana = lastFuriganaLen > 0 ? f.slice(0, lastFuriganaLen) : "";
  const first_furigana =
    lastFuriganaLen > 0 ? f.slice(lastFuriganaLen) : f;

  return {
    last_name,
    first_name,
    last_furigana,
    first_furigana,
  };
}

/** 簡易 CSV パース（ダブルクォート内のカンマは考慮しない） */
function parseCsvRow(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') {
      inQuotes = !inQuotes;
    } else if ((c === "," && !inQuotes) || (c === "\n" && !inQuotes)) {
      result.push(current);
      current = "";
      if (c === "\n") break;
    } else {
      current += c;
    }
  }
  result.push(current);
  return result;
}

function escapeSql(s: string): string {
  return s.replace(/'/g, "''");
}

function main(): void {
  const content = fs.readFileSync(CSV_PATH, "utf-8");
  const lines = content.split(/\r?\n/).filter((l) => l.trim());
  if (lines.length < 2) {
    console.error("CSV has no header or rows.");
    process.exit(1);
  }

  const header = parseCsvRow(lines[0]!);
  const nameIdx = header.indexOf("name");
  const furiganaIdx = header.indexOf("furigana");
  const idIdx = header.indexOf("id");
  if (nameIdx < 0 || idIdx < 0) {
    console.error("CSV must have 'id' and 'name' columns.");
    process.exit(1);
  }

  console.log("-- Generated by scripts/split-members-name.ts");
  console.log("-- Run after applying migration 045_members_first_last_name.sql");
  console.log("BEGIN;");

  for (let i = 1; i < lines.length; i++) {
    const row = parseCsvRow(lines[i]!);
    const id = row[idIdx]?.trim();
    const name = row[nameIdx]?.trim() ?? "";
    const furigana =
      furiganaIdx >= 0 ? (row[furiganaIdx]?.trim() ?? null) : null;
    if (!id) continue;

    const { last_name, first_name, last_furigana, first_furigana } =
      splitNameAndFurigana(name, furigana);

    const sql = [
      `last_name = ${last_name ? `'${escapeSql(last_name)}'` : "NULL"}`,
      `first_name = ${first_name ? `'${escapeSql(first_name)}'` : "NULL"}`,
      `last_furigana = ${last_furigana ? `'${escapeSql(last_furigana)}'` : "NULL"}`,
      `first_furigana = ${first_furigana ? `'${escapeSql(first_furigana)}'` : "NULL"}`,
    ].join(", ");
    console.log(`UPDATE members SET ${sql} WHERE id = '${escapeSql(id)}';`);
  }

  console.log("COMMIT;");
}

main();
